sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t alejandropm/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true alejandropm/react-test npm test

after_success:
    - docker build -t alejandropm/multi-client ./client
    - docker build -t alejandropm/multi-nginx ./nginx
    - docker build -t alejandropm/multi-server ./server
    - docker build -t alejandropm/multi-worker ./worker
    # Log in to the docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # we push stuff 
    - docker push alejandropm/multi-client
    - docker push alejandropm/multi-nginx
    - docker push alejandropm/multi-server
    - docker push alejandropm/multi-worker

deploy:
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-285504358899
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
# access_key_id: $AWS_ACCESS_KEY
# secret_access_key: $AWS_SECRET_KEY

# deploy:
#   edge: true
#   provider: elasticbeanstalk
#   ...